---
- name: Set DNS
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: "644"
    attributes: +i

- name: Check that powerdns recursor runs
  wait_for: host=127.0.0.1 port=5353 timeout=3

- name: Configure dnsdist
  template:
    src: dnsdist.conf.j2
    dest: /etc/dnsdist/dnsdist.conf
    mode: "644"
  notify: restart dnsdist
