- hosts: radicaldns
  become: yes
  gather_facts: yes

  vars_files:
    - private.yml

  vars:
    TEST_DOMAIN: "test.libreops.cc"

  roles:
    - common
    - pdns_recursor
    - dnsdist
    - opennic
