---
- name: Install python packages
  apt:
    pkg:
    - python3-bs4
    - python3-requests
    state: present
    install_recommends: no

- name: Copy script and timer
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - {
      src: "opennic-check.py.j2",
      dest: "/usr/local/bin/opennic-check.py",
      mode: "755"
    }
    - {
      src: "opennic-check.timer.j2",
      dest: "/etc/systemd/system/opennic-check.timer",
      mode: "644"
    }
    - {
      src: "opennic-check.service.j2",
      dest: "/etc/systemd/system/opennic-check.service",
      mode: "644"
    }

- name: Enable opennic-check timer
  systemd:
    name: opennic-check.timer
    state: started
    enabled: yes
