---
- name: Install node_exporter packages
  apt:
    pkg:
    - prometheus-node-exporter
    - apache2-utils
    - python3-passlib

- name: Generate htpasswd entries
  htpasswd:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    path: "{{ auth_path }}"
    owner: root
    group: www-data
    mode: "640"
  with_items:
    - {
      name: "{{ node_exporter_username }}",
      password: "{{ node_exporter_password }}"
    }
    - {
      name: "{{ dnsdist_web_username }}",
      password: "{{ dnsdist_web_password }}"
    }

- name: Copy nginx snippets
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "644"
  with_items:
    - {
      src: "node_exporter.conf.j2",
      dest: "/etc/nginx/snippets/node_exporter.conf"
    }
    - {
      src: "dnsdist.conf.j2",
      dest: "/etc/nginx/snippets/dnsdist.conf"
    }
  notify:
    - restart nginx
