---
- name: Install Packages
  apt:
    pkg:
    - mlocate
    - vim
    - bash-completion
    - screenfetch
    - postfix
    state: present

- name: Set hostname
  hostname: name={{ inventory_hostname }}

- name: Reset timezone
  timezone: name=UTC

- name: Run locate
  command: updatedb
  when: True

- name: Disable Ubuntu's motd scripts
  file:
    path: /etc/update-motd.d
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Adjust motd message
  file:
    src: /usr/bin/screenfetch
    dest: /etc/update-motd.d/90-screenfetch
    owner: root
    group: root
    state: link

- name: Enable UFW and reject everything
  ufw:
    state: enabled
    policy: reject

- name: UFW enable ssh
  ufw:
    rule: allow
    port: "{{ hostvars[inventory_hostname].ansible_port }}"

- name: Set floating IP
  template:
    src: 60-floating-ip.yaml.j2
    dest: /etc/netplan/60-floating-ip.yaml
    owner: root
    group: root
    mode: 0644
  notify:
    - restart networking

- import_tasks: mail.yml

- import_tasks: swap.yml

- import_tasks: dns.yml
