---
- name: PowerDNS Configuration
  template:
    src: recursor.conf.j2
    dest: /etc/powerdns/recursor.conf
    owner: root
    group: pdns
    mode: "644"

- name: Copy all scripts and timers
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - {
      src: "root-hints.sh.j2",
      dest: "/usr/local/bin/root-hints.sh",
      mode: "755"
    }
    - {
      src: "root-hints.timer.j2",
      dest: "/etc/systemd/system/root-hints.timer",
      mode: "644"
    }
    - {
      src: "root-hints.service.j2",
      dest: "/etc/systemd/system/root-hints.service",
      mode: "644"
    }
    - {
      src: "opennic-zones.sh.j2",
      dest: "/usr/local/bin/opennic-zones.sh",
      mode: "755"
    }
    - {
      src: "opennic-zones.timer.j2",
      dest: "/etc/systemd/system/opennic-zones.timer",
      mode: "644"
    }
    - {
      src: "opennic-zones.service.j2",
      dest: "/etc/systemd/system/opennic-zones.service",
      mode: "644"
    }

- name: Create zones directory
  file:
    path: /etc/powerdns/zones.d/
    state: directory
    owner: pdns
    group: pdns
    mode: "755"

- name: Enable DNS timers
  systemd:
    name: "{{ item.name }}"
    state: started
    enabled: yes
  with_items:
    - {
      name: "opennic-zones.timer"
    }
    - {
      name: "root-hints.timer"
    }

- name: Update root hints
  command: /usr/local/bin/root-hints.sh
  args:
    creates: /etc/powerdns/root.hints
  become: yes

- name: Update zones
  command: /usr/local/bin/opennic-zones.sh
  args:
    creates: /etc/powerdns/zones.d/opennic.glue.conf
  become: yes
  notify: restart pdns-recursor
