---
- name: PowerDNS Configuration
  template:
    src: recursor.conf.j2
    dest: /etc/powerdns/recursor.conf
    owner: root
    group: pdns
    mode: 0644

- name: Check if root hints exist
  stat:
    path: "/etc/powerdns/root.hints"
  register: stat_result

- name: Update root hint
  shell: |
    set -o pipefail
    OPENIC_ROOTNS=$(curl -sL 'https://api.opennicproject.org/geoip/?bare&res=1')
    dig . NS @{ OPENIC_ROOTNS } | egrep -v '^;|^$' > /etc/powerdns/root.hints
  args:
    executable: /bin/bash
  when: not stat_result.stat.exists

- name: Copy Opennic zones scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - {
      src: "opennic-zones.sh.j2",
      dest: "/usr/local/bin/opennic-zones.sh",
      mode: 0755
    }
    - {
      src: "opennic-zones.timer.j2",
      dest: "/etc/systemd/system/opennic-zones.timer",
      mode: 0644
    }
    - {
      src: "opennic-zones.service.j2",
      dest: "/etc/systemd/system/opennic-zones.service",
      mode: 0644
    }

- name: Create zones directory
  file:
    path: /etc/powerdns/zones.d/
    state: directory
    owner: pdns
    group: pdns
    mode: 0755

- name: Enable Openic zones timer
  systemd:
    name: opennic-zones.timer
    state: started
    enabled: yes

- name: Update zones
  command: /usr/local/bin/opennic-zones.sh
  args:
    creates: /etc/powerdns/zones.d/opennic.glue.conf
  become: yes
  become_user: pdns
  notify: restart pdns-recursor
