---
- name: Download StevenBlack hosts
  get_url:
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    dest: /etc/powerdns/hosts.txt
    force: yes
    mode: "644"
    owner: pdns
    group: pdns

- name: Copy update StevenBlack hosts script
  copy:
    src: update.stevenblack.hosts.sh
    dest: /usr/local/bin/update.stevenBlack.hosts.sh
    mode: "750"

- name: Add StevenBlack hosts renewal timer
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "644"
  with_items:
    - {
      src: "stevenblack-hosts.timer.j2",
      dest: "/etc/systemd/system/stevenblack-hosts.timer",
    }
    - {
      src: "stevenblack-hosts.service.j2",
      dest: "/etc/systemd/system/stevenblack-hosts.service",
    }

- name: Enable StevenBlack hosts renewal timer
  systemd:
    name: stevenblack-hosts.timer
    state: started
    enabled: yes
